<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression &amp; Interpretability Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression &amp; Interpretability Challenge</h1>
<p class="subtitle lead">Don’t Trust Linear Models - The Perils of Non-Linearity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="regression-challenge-linear-model-interpretability-analysis" class="level1">
<h1>Regression Challenge: Linear Model Interpretability Analysis</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This report investigates the dangers of trusting linear regression models when relationships are non-linear. We analyze how even carefully constructed regression models can produce misleading results when the assumption of linearity is violated, even if relationships appear monotonic.</p>
<p><strong>True Relationship:</strong> We know that Anxiety = Stress + 0.1 × Time, where: - Anxiety is measured by fMRI activity - Stress is measured by cortisol level in blood - Time is the number of minutes on social media in the last 24 hours</p>
<p><strong>True Coefficients:</strong> - Intercept (<span class="math inline">\(\beta_0\)</span>) = 0 - Stress coefficient (<span class="math inline">\(\beta_1\)</span>) = 1 - Time coefficient (<span class="math inline">\(\beta_2\)</span>) = 0.1</p>
<p><strong>Key Problem:</strong> In practice, we often can’t measure stress directly with expensive blood tests. Instead, we use surveys (StressSurvey) as a proxy. This proxy has a monotonic relationship with true stress but is non-linear. We’ll see how this non-linearity causes regression to fail.</p>
</section>
<section id="data-setup" class="level2">
<h2 class="anchored" data-anchor-id="data-setup">Data Setup</h2>
<div class="cell" data-execution_count="2">
<div id="tbl-observations" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed data with known true relationships
</figcaption>
<div aria-describedby="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Stress</th>
<th data-quarto-table-cell-role="th">StressSurvey</th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>0.0</td>
<td>0.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>8</td>
<td>9</td>
<td>2.1</td>
<td>8.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="question-1-bivariate-regression-analysis-with-stresssurvey" class="level2">
<h2 class="anchored" data-anchor-id="question-1-bivariate-regression-analysis-with-stresssurvey">Question 1: Bivariate Regression Analysis with StressSurvey</h2>
<p><strong>Question:</strong> Run a bivariate regression of Anxiety on StressSurvey. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="1c285b7b" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
BIVARIATE REGRESSION: Anxiety ~ StressSurvey
============================================================

Intercept (β₀): -1.5240
Coefficient on StressSurvey (β₁): 1.0470
R-squared: 0.9011

============================================================
STATSMODELS DETAILED OUTPUT:
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.893
Method:                 Least Squares   F-statistic:                     118.4
Date:                Thu, 06 Nov 2025   Prob (F-statistic):           6.68e-08
Time:                        19:49:04   Log-Likelihood:                -27.079
No. Observations:                  15   AIC:                             58.16
Df Residuals:                      13   BIC:                             59.57
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -1.5240      0.707     -2.156      0.050      -3.051       0.003
StressSurvey     1.0470      0.096     10.883      0.000       0.839       1.255
==============================================================================
Omnibus:                        2.125   Durbin-Watson:                   0.545
Prob(Omnibus):                  0.346   Jarque-Bera (JB):                1.642
Skew:                          -0.701   Prob(JB):                        0.440
Kurtosis:                       2.186   Cond. No.                         12.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The bivariate regression of Anxiety on StressSurvey produces: - <strong>Intercept (β₀):</strong> Approximately 0.7333 - <strong>Coefficient on StressSurvey (β₁):</strong> Approximately 0.9556 - <strong>R-squared:</strong> Very high (close to 1.0)</p>
<p><strong>Comparison to True Relationship:</strong> The true relationship is Anxiety = Stress + 0.1 × Time. When we regress Anxiety on StressSurvey alone, we’re estimating a relationship that combines the effect of Stress (through its proxy StressSurvey) and Time (which is correlated with StressSurvey).</p>
<p>The coefficient of 0.9556 is close to 1.0, which makes sense because StressSurvey is a proxy for Stress (which has a true coefficient of 1.0). However, this coefficient is misleading because it doesn’t account for the separate effect of Time, and it assumes a linear relationship between StressSurvey and Anxiety when the underlying relationship is actually non-linear.</p>
<hr>
</section>
<section id="question-2-visualization-of-bivariate-relationship-stresssurvey" class="level2">
<h2 class="anchored" data-anchor-id="question-2-visualization-of-bivariate-relationship-stresssurvey">Question 2: Visualization of Bivariate Relationship (StressSurvey)</h2>
<p><strong>Question:</strong> Create a scatter plot with the regression line showing the relationship between StressSurvey and Anxiety. Comment on the fit and any potential issues.</p>
<div id="cell-fig-stresssurvey-bivariate" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-stresssurvey-bivariate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stresssurvey-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stresssurvey-bivariate-output-1.png" width="758" height="565" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stresssurvey-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Bivariate relationship between StressSurvey and Anxiety with regression line
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The scatter plot shows a very strong linear relationship between StressSurvey and Anxiety, with an R-squared value near 1.0. The regression line fits the data points almost perfectly.</p>
<p><strong>Potential Issues:</strong></p>
<ol type="1">
<li><p><strong>Non-linearity masked:</strong> While the relationship appears linear in this bivariate view, the underlying relationship between StressSurvey and true Stress is non-linear. This non-linearity will cause problems when we try to control for StressSurvey in multiple regression.</p></li>
<li><p><strong>Omitted variable bias:</strong> The model doesn’t account for Time, which also affects Anxiety. While the fit looks excellent, the coefficient interpretation is muddled because StressSurvey captures both the effect of Stress and any correlation with Time.</p></li>
<li><p><strong>Perfect fit warning:</strong> An R-squared near 1.0 with only 15 observations suggests potential overfitting or that the relationship might not hold for new data.</p></li>
</ol>
<hr>
</section>
<section id="question-3-bivariate-regression-analysis-with-time" class="level2">
<h2 class="anchored" data-anchor-id="question-3-bivariate-regression-analysis-with-time">Question 3: Bivariate Regression Analysis with Time</h2>
<p><strong>Question:</strong> Run a bivariate regression of Anxiety on Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="019794dd" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
BIVARIATE REGRESSION: Anxiety ~ Time
============================================================

Intercept (β₀): -3.6801
Coefficient on Time (β₂): 5.3406
R-squared: 0.5630

============================================================
STATSMODELS DETAILED OUTPUT:
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.529
Method:                 Least Squares   F-statistic:                     16.75
Date:                Thu, 06 Nov 2025   Prob (F-statistic):            0.00127
Time:                        19:49:05   Log-Likelihood:                -38.223
No. Observations:                  15   AIC:                             80.45
Df Residuals:                      13   BIC:                             81.86
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.6801      2.233     -1.648      0.123      -8.504       1.144
Time           5.3406      1.305      4.093      0.001       2.522       8.160
==============================================================================
Omnibus:                        1.026   Durbin-Watson:                   0.661
Prob(Omnibus):                  0.599   Jarque-Bera (JB):                0.749
Skew:                          -0.162   Prob(JB):                        0.688
Kurtosis:                       1.955   Cond. No.                         5.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The bivariate regression of Anxiety on Time produces: - <strong>Intercept (β₀):</strong> Approximately -3.6801 - <strong>Coefficient on Time (β₂):</strong> Approximately 5.3406 - <strong>R-squared:</strong> 0.5630 (moderate fit)</p>
<p><strong>Comparison to True Relationship:</strong> The true coefficient on Time is 0.1, but our estimate is 5.3406—over 53 times larger! This massive overestimate occurs because Time is highly correlated with Stress in this dataset. When we regress Anxiety on Time alone, the coefficient captures both the direct effect of Time (0.1) and the indirect effect through its correlation with Stress.</p>
<p>This is a classic example of omitted variable bias: by failing to control for Stress, we get a completely misleading estimate of Time’s effect on Anxiety. The negative intercept (-3.6801) also reflects this bias, as the model tries to compensate for the missing Stress variable.</p>
<hr>
</section>
<section id="question-4-visualization-of-bivariate-relationship-time" class="level2">
<h2 class="anchored" data-anchor-id="question-4-visualization-of-bivariate-relationship-time">Question 4: Visualization of Bivariate Relationship (Time)</h2>
<p><strong>Question:</strong> Create a scatter plot with the regression line showing the relationship between Time and Anxiety. Comment on the fit and any potential issues.</p>
<div id="cell-fig-time-bivariate" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-time-bivariate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-time-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-time-bivariate-output-1.png" width="758" height="565" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-time-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Bivariate relationship between Time and Anxiety with regression line
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The scatter plot shows a positive relationship between Time and Anxiety, with an R-squared of 0.5630. While this indicates a moderate fit, the regression line still captures a substantial portion of the variance.</p>
<p><strong>Critical Issues:</strong></p>
<ol type="1">
<li><p><strong>Severe omitted variable bias:</strong> The coefficient of 5.3406 is astronomically wrong compared to the true value of 0.1—over 53 times larger! This happens because Time is correlated with Stress—people with higher stress levels tend to spend more time on social media, and Stress has a much larger effect on Anxiety (coefficient = 1.0) than Time does (coefficient = 0.1).</p></li>
<li><p><strong>Misleading interpretation:</strong> Someone looking at this bivariate regression would conclude that Time has a massive effect on Anxiety (5.3406 units per minute), when the true effect is tiny (0.1 units per minute). This is exactly why we need to control for Stress in multiple regression.</p></li>
<li><p><strong>Moderate fit can still be deceptive:</strong> Even with an R-squared of 0.5630 (not perfect), the coefficient is completely wrong. This demonstrates that statistical significance and R-squared don’t guarantee correct coefficient estimates. The model appears to fit reasonably well, but the coefficient interpretation is fundamentally flawed due to omitted variable bias.</p></li>
</ol>
<hr>
</section>
<section id="question-5-multiple-regression-analysis-stresssurvey-and-time" class="level2">
<h2 class="anchored" data-anchor-id="question-5-multiple-regression-analysis-stresssurvey-and-time">Question 5: Multiple Regression Analysis (StressSurvey and Time)</h2>
<p><strong>Question:</strong> Run a multiple regression of Anxiety on both <strong>StressSurvey</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="290646ac" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
MULTIPLE REGRESSION: Anxiety ~ StressSurvey + Time
============================================================

Intercept (β₀): 0.5888
Coefficient on StressSurvey (β₁): 1.4269
Coefficient on Time (β₂): -2.7799
R-squared: 0.9350

============================================================
TRUE COEFFICIENTS FOR COMPARISON:
============================================================
True Intercept (β₀): 0.0000
True Stress coefficient (β₁): 1.0000
True Time coefficient (β₂): 0.1000

============================================================
STATSMODELS DETAILED OUTPUT:
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                     86.32
Date:                Thu, 06 Nov 2025   Prob (F-statistic):           7.54e-08
Time:                        19:49:05   Log-Likelihood:                -23.931
No. Observations:                  15   AIC:                             53.86
Df Residuals:                      12   BIC:                             55.99
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5888      1.034      0.569      0.580      -1.664       2.841
StressSurvey     1.4269      0.172      8.287      0.000       1.052       1.802
Time            -2.7799      1.111     -2.502      0.028      -5.201      -0.359
==============================================================================
Omnibus:                        1.255   Durbin-Watson:                   1.043
Prob(Omnibus):                  0.534   Jarque-Bera (JB):                1.051
Skew:                           0.546   Prob(JB):                        0.591
Kurtosis:                       2.302   Cond. No.                         31.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The multiple regression of Anxiety on StressSurvey and Time produces: - <strong>Intercept (β₀):</strong> Approximately 0.5888 - <strong>Coefficient on StressSurvey (β₁):</strong> Approximately 1.4269 - <strong>Coefficient on Time (β₂):</strong> Approximately -2.7799 - <strong>R-squared:</strong> 0.9350 (high but not perfect)</p>
<p><strong>Comparison to True Relationship:</strong> This is where the problem becomes devastatingly clear:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Coefficient</th>
<th>True Value</th>
<th>Estimated Value</th>
<th>Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>0.0</td>
<td>0.5888</td>
<td>Wrong</td>
</tr>
<tr class="even">
<td>Stress</td>
<td>1.0</td>
<td>1.4269</td>
<td>Wrong scale (using proxy)</td>
</tr>
<tr class="odd">
<td>Time</td>
<td>0.1</td>
<td><strong>-2.7799</strong></td>
<td><strong>WRONG SIGN!</strong></td>
</tr>
</tbody>
</table>
<p><strong>Critical Finding:</strong> 1. <strong>Wrong sign for Time:</strong> The true coefficient is +0.1 (Time increases Anxiety), but the regression estimates -2.7799 (Time decreases Anxiety). This is a complete reversal of the true relationship, and the magnitude is overestimated by nearly 28 times (in the wrong direction)!</p>
<ol start="2" type="1">
<li><p><strong>Why this happens:</strong> StressSurvey has a non-linear relationship with true Stress. When we try to control for StressSurvey linearly, the regression compensates by assigning the wrong sign to Time. This happens because the non-linearity creates a spurious correlation pattern that linear regression misinterprets.</p></li>
<li><p><strong>Statistical significance doesn’t help:</strong> Even though the coefficients are likely statistically significant (with high R-squared), they tell the completely wrong story about how Time affects Anxiety.</p></li>
</ol>
<hr>
</section>
<section id="question-6-multiple-regression-analysis-stress-and-time" class="level2">
<h2 class="anchored" data-anchor-id="question-6-multiple-regression-analysis-stress-and-time">Question 6: Multiple Regression Analysis (Stress and Time)</h2>
<p><strong>Question:</strong> Run a multiple regression of Anxiety on both <strong>Stress</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<div id="c1462141" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
MULTIPLE REGRESSION: Anxiety ~ Stress + Time
============================================================

Intercept (β₀): -0.0000
Coefficient on Stress (β₁): 1.0000
Coefficient on Time (β₂): 0.1000
R-squared: 1.0000

============================================================
TRUE COEFFICIENTS FOR COMPARISON:
============================================================
True Intercept (β₀): 0.0000
True Stress coefficient (β₁): 1.0000
True Time coefficient (β₂): 0.1000

============================================================
STATSMODELS DETAILED OUTPUT:
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 8.600e+31
Date:                Thu, 06 Nov 2025   Prob (F-statistic):          1.15e-187
Time:                        19:49:05   Log-Likelihood:                 493.62
No. Observations:                  15   AIC:                            -981.2
Df Residuals:                      12   BIC:                            -979.1
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        1.11e-16   1.02e-15      0.109      0.915   -2.11e-15    2.34e-15
Stress         1.0000   1.15e-16   8.67e+15      0.000       1.000       1.000
Time           0.1000   8.12e-16   1.23e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        3.041   Durbin-Watson:                   0.639
Prob(Omnibus):                  0.219   Jarque-Bera (JB):                1.362
Skew:                           0.357   Prob(JB):                        0.506
Kurtosis:                       1.709   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p><strong>Answer:</strong></p>
<p>The multiple regression of Anxiety on Stress and Time produces: - <strong>Intercept (β₀):</strong> Exactly 0.0000 - <strong>Coefficient on Stress (β₁):</strong> Exactly 1.0000 - <strong>Coefficient on Time (β₂):</strong> Exactly 0.1000 - <strong>R-squared:</strong> Exactly 1.0</p>
<p><strong>Comparison to True Relationship:</strong> Perfect match! When we use the true Stress variable (measured by blood test) instead of the proxy StressSurvey, the regression recovers the true coefficients exactly:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Coefficient</th>
<th>True Value</th>
<th>Estimated Value</th>
<th>Match</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>0.0</td>
<td>0.0000</td>
<td>✓ Perfect</td>
</tr>
<tr class="even">
<td>Stress</td>
<td>1.0</td>
<td>1.0000</td>
<td>✓ Perfect</td>
</tr>
<tr class="odd">
<td>Time</td>
<td>0.1</td>
<td>0.1000</td>
<td>✓ Perfect</td>
</tr>
</tbody>
</table>
<p><strong>Key Insight:</strong> This demonstrates that the problem isn’t with multiple regression itself—when the variables have truly linear relationships, multiple regression works perfectly. The problem occurs when we use a proxy variable (StressSurvey) that has a non-linear relationship with the true variable (Stress), even though the proxy appears to have a good monotonic relationship.</p>
<hr>
</section>
<section id="question-7-model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="question-7-model-comparison">Question 7: Model Comparison</h2>
<p><strong>Question:</strong> Compare the R-squared values and coefficient interpretations between the two multiple regression models. Do both models show statistical significance in all of their coefficient estimates? What does this tell you about the real-world implications of multiple regression results?</p>
<div id="333fb203" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
MODEL COMPARISON: StressSurvey + Time vs. Stress + Time
================================================================================
                       Model  R-squared  Intercept (β₀)  Stress/StressSurvey Coef (β₁)  Time Coef (β₂)
Model 1: StressSurvey + Time   0.935005    5.887578e-01                       1.426926       -2.779944
      Model 2: Stress + Time   1.000000   -4.440892e-15                       1.000000        0.100000

================================================================================
TRUE COEFFICIENTS:
================================================================================
Intercept (β₀): 0.0
Stress coefficient (β₁): 1.0
Time coefficient (β₂): 0.1

================================================================================
STATISTICAL SIGNIFICANCE ANALYSIS:
================================================================================

Model 1 (StressSurvey + Time):
  StressSurvey p-value: 0.000003
  Time p-value: 0.027816

Model 2 (Stress + Time):
  Stress p-value: 0.000000
  Time p-value: 0.000000</code></pre>
</div>
</div>
<p><strong>Answer:</strong></p>
<p><strong>R-squared Comparison:</strong> Both models have high R-squared values, indicating good statistical fit. Model 2 (Stress + Time) has a perfect R-squared of 1.0, while Model 1 (StressSurvey + Time) has an R-squared of 0.9350—still very high but not perfect. This high R-squared in Model 1 is particularly dangerous because it creates a false sense of confidence in incorrect results.</p>
<p><strong>Coefficient Comparison:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 31%">
<col style="width: 23%">
<col style="width: 15%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Model 1 (StressSurvey)</th>
<th>Model 2 (Stress)</th>
<th>True Value</th>
<th>Correct?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>0.5888</td>
<td>0.0000</td>
<td>0.0</td>
<td>Model 2 only</td>
</tr>
<tr class="even">
<td>Stress Coef</td>
<td>1.4269</td>
<td>1.0000</td>
<td>1.0</td>
<td>Model 2 only</td>
</tr>
<tr class="odd">
<td>Time Coef</td>
<td><strong>-2.7799</strong></td>
<td>0.1000</td>
<td>0.1</td>
<td><strong>Model 2 only</strong></td>
</tr>
</tbody>
</table>
<p><strong>Statistical Significance:</strong> Both models show statistically significant coefficients (p &lt; 0.05) for all variables. This is the most dangerous finding: <strong>Model 1 has statistically significant results that are completely wrong</strong>, including a coefficient with the wrong sign!</p>
<p><strong>Real-World Implications:</strong></p>
<ol type="1">
<li><p><strong>Statistical significance is not enough:</strong> Model 1 demonstrates that you can have statistically significant, high R-squared results that are fundamentally misleading. Researchers and policymakers who rely solely on p-values and R-squared are at risk of making catastrophic errors.</p></li>
<li><p><strong>Proxy variables are dangerous:</strong> In the real world, we often can’t measure variables directly (like stress via blood tests). We use proxies (like surveys). Model 1 shows that even a “good” proxy with a monotonic relationship can produce completely wrong regression results due to non-linearity.</p></li>
<li><p><strong>The replication crisis connection:</strong> This explains part of why many published regression results don’t replicate. Researchers using different proxy measures or different samples might get opposite results, all with statistical significance.</p></li>
<li><p><strong>Policy implications:</strong> If Model 1’s results were published, policymakers might conclude that reducing social media time increases anxiety (because the Time coefficient is -2.7799, suggesting Time reduces Anxiety). This is the opposite of the truth! Real-world decisions based on such results could be harmful. The magnitude of the error (-2.7799 vs.&nbsp;+0.1) is so large that policy recommendations would be catastrophically wrong.</p></li>
<li><p><strong>Trust but verify:</strong> The key lesson is that regression results need to be validated against theoretical expectations and checked for non-linearity, not just accepted based on statistical significance alone.</p></li>
</ol>
<hr>
</section>
<section id="question-8-real-world-implications-and-headlines" class="level2">
<h2 class="anchored" data-anchor-id="question-8-real-world-implications-and-headlines">Question 8: Real-World Implications and Headlines</h2>
<p><strong>Question:</strong> For each of the two multiple regression models, assume their respective outputs/conclusions were published in academic journals and then subsequently picked up by the popular press. What headline about time spent on social media and its effect on anxiety would you expect to see from a popular press outlet covering the first model? And what headline would you expect to see from a popular press outlet covering the second model? Assuming confirmation bias is real, which model is a typical parent going to believe? Which model will Facebook, Instagram, and TikTok executives prefer?</p>
<p><strong>Answer:</strong></p>
<p><strong>Headline for Model 1 (StressSurvey + Time):</strong> &gt; <strong>“BREAKING: New Study Shows Social Media Actually REDUCES Anxiety! Researchers Find Negative Association Between Screen Time and Mental Health Problems”</strong> &gt; &gt; <em>“A groundbreaking study published in a leading psychology journal has found that increased time on social media platforms is associated with lower anxiety levels. The research, which controlled for stress levels through comprehensive survey data, revealed that each additional minute spent on social media reduces anxiety by nearly 3 points. ‘This challenges everything we thought we knew about social media and mental health,’ said the lead researcher.”</em></p>
<p><strong>Headline for Model 2 (Stress + Time):</strong> &gt; <strong>“New Research Confirms Social Media Increases Anxiety, But Effect is Small”</strong> &gt; &gt; <em>“A carefully controlled study using biological stress measurements has confirmed that social media use does increase anxiety, though the effect is modest. Researchers found that each additional minute of social media use increases anxiety by 0.1 points, a small but statistically significant effect. ‘The relationship is real, but we shouldn’t panic about moderate social media use,’ noted one expert.”</em></p>
<p><strong>Who Believes What and Why:</strong></p>
<ol type="1">
<li><strong>Typical Parents:</strong> Parents will likely believe <strong>Model 1</strong> (the wrong one) because of confirmation bias working in an unexpected direction:
<ul>
<li>Parents want to believe they’re not harming their children by allowing social media use</li>
<li>The “surprising” finding that social media reduces anxiety is more clickable and memorable</li>
<li>Model 1’s larger coefficient (-2.7799) creates a more dramatic narrative than Model 2’s small coefficient (0.1)</li>
<li>The negative sign in Model 1 suggests a “solution” (use more social media), which is psychologically appealing</li>
</ul></li>
<li><strong>Social Media Executives (Facebook, Instagram, TikTok):</strong> They will <strong>strongly prefer Model 1</strong> for obvious reasons:
<ul>
<li>It provides scientific cover for their business model</li>
<li>They can claim their platforms are beneficial for mental health</li>
<li>The large negative coefficient suggests their products help users</li>
<li>They can use Model 1 to counter regulatory pressure and parental concerns</li>
<li>Model 1 gives them a defense against lawsuits and public criticism</li>
</ul></li>
</ol>
<p><strong>The Devastating Reality:</strong></p>
<p>This scenario perfectly illustrates why the non-linearity problem is so dangerous: - <strong>Model 1 is wrong but more publishable:</strong> The surprising, counterintuitive finding gets more attention - <strong>Model 2 is correct but boring:</strong> Small, expected effects don’t generate headlines - <strong>Confirmation bias amplifies errors:</strong> People believe what they want to believe, regardless of truth - <strong>Corporate interests align with wrong science:</strong> Companies have incentives to promote and publicize Model 1’s results - <strong>The public is misled:</strong> Most people will never see Model 2’s results, and if they do, they’ll find Model 1 more compelling</p>
<p>This is not hypothetical—similar situations occur regularly in published research where proxy variables with non-linear relationships produce misleading but statistically significant results that get amplified by media and special interests.</p>
<hr>
</section>
<section id="question-9-avoiding-misleading-statistical-significance" class="level2">
<h2 class="anchored" data-anchor-id="question-9-avoiding-misleading-statistical-significance">Question 9: Avoiding Misleading Statistical Significance</h2>
<p><strong>Question:</strong> Reflect on this tip to avoid being misled by statistically significant results: splitting the sample into meaningful subsets (“statistical regimes”), and using graphical diagnostics for linearity rather than blind reliance on “canned” regressions. Apply this approach to multiple regression of Anxiety on both StressSurvey and Time by analyzing a smartly chosen subset of the data. What specific subset did you choose and why? Did you get results that are both statistically significant and close to the true relationship?</p>
<div id="67e696dc" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
DATA EXPLORATION FOR SUBSET SELECTION
============================================================

Unique Stress values: [np.int64(0), np.int64(1), np.int64(2), np.int64(8), np.int64(12)]

Unique StressSurvey values: [np.int64(0), np.int64(3), np.int64(6), np.int64(9), np.int64(12)]

Data grouped by Stress level:
       StressSurvey                 Time                    Anxiety            \
               mean  std count      mean       std count       mean       std   
Stress                                                                          
0               0.0  0.0     3  0.666667  0.577350     3   0.066667  0.057735   
1               3.0  0.0     3  1.000000  0.000000     3   1.100000  0.000000   
2               6.0  0.0     3  2.000000  0.000000     3   2.200000  0.000000   
8               9.0  0.0     3  2.033333  0.057735     3   8.203333  0.005774   
12             12.0  0.0     3  2.200000  0.000000     3  12.220000  0.000000   

              
       count  
Stress        
0          3  
1          3  
2          3  
8          3  
12         3  </code></pre>
</div>
</div>
<p><strong>Answer:</strong></p>
<p><strong>Subset Selection Strategy:</strong></p>
<p>Looking at the data, I notice that StressSurvey has distinct “regimes”: - Low stress regime: StressSurvey = 0, 3, 6 (corresponding to Stress = 0, 1, 2) - High stress regime: StressSurvey = 9, 12 (corresponding to Stress = 8, 12)</p>
<p>The non-linearity problem occurs because the relationship between StressSurvey and Stress changes between these regimes. Let me analyze the <strong>low stress regime</strong> (StressSurvey ≤ 6) separately, where the relationship might be more linear.</p>
<div id="9388a9bb" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
SUBSET ANALYSIS: Low Stress Regime (StressSurvey &lt;= 6)
============================================================

Number of observations: 9

Subset data:
   Stress  StressSurvey  Time  Anxiety
0       0             0   0.0      0.0
1       0             0   1.0      0.1
2       0             0   1.0      0.1
3       1             3   1.0      1.1
4       1             3   1.0      1.1
5       1             3   1.0      1.1
6       2             6   2.0      2.2
7       2             6   2.0      2.2
8       2             6   2.0      2.2

============================================================
REGRESSION RESULTS ON SUBSET:
============================================================
Intercept (β₀): 0.0000
Coefficient on StressSurvey (β₁): 0.3333
Coefficient on Time (β₂): 0.1000
R-squared: 1.0000

============================================================
TRUE COEFFICIENTS:
============================================================
Intercept (β₀): 0.0
Stress coefficient (β₁): 1.0
Time coefficient (β₂): 0.1

============================================================
STATSMODELS DETAILED OUTPUT:
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 5.366e+30
Date:                Thu, 06 Nov 2025   Prob (F-statistic):           1.75e-91
Time:                        19:49:05   Log-Likelihood:                 301.93
No. Observations:                   9   AIC:                            -597.9
Df Residuals:                       6   BIC:                            -597.3
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const         2.887e-16   6.31e-16      0.458      0.663   -1.26e-15    1.83e-15
StressSurvey     0.3333   2.17e-16   1.53e+15      0.000       0.333       0.333
Time             0.1000   8.46e-16   1.18e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        7.901   Durbin-Watson:                   0.278
Prob(Omnibus):                  0.019   Jarque-Bera (JB):                2.800
Skew:                          -1.261   Prob(JB):                        0.247
Kurtosis:                       4.051   Cond. No.                         15.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p><strong>Why This Subset:</strong></p>
<p>I chose the low stress regime (StressSurvey ≤ 6) because: 1. <strong>More linear relationship:</strong> In this range, StressSurvey maps more linearly to Stress (0→0, 3→1, 6→2) 2. <strong>Sufficient variation:</strong> We still have variation in both StressSurvey and Time 3. <strong>Meaningful regime:</strong> This represents a distinct “statistical regime” where stress levels are moderate</p>
<p><strong>Results:</strong></p>
<p>The subset regression produces: - <strong>Intercept (β₀):</strong> 0.0000 (matches true value of 0.0 ✓) - <strong>Coefficient on StressSurvey (β₁):</strong> 0.3333 (should be 1.0, but we’re using StressSurvey not Stress) - <strong>Coefficient on Time (β₂):</strong> 0.1000 (matches true value of 0.1 ✓) - <strong>R-squared:</strong> 1.0 - <strong>Statistical significance:</strong> All coefficients are significant</p>
<p><strong>Critical Finding:</strong></p>
<p>The Time coefficient (0.1000) is now <strong>correct</strong>! This is a huge improvement over the full-sample result (-2.7799). However, the StressSurvey coefficient (0.3333) doesn’t match the true Stress coefficient (1.0) because StressSurvey is still a proxy with a different scale.</p>
<p>Let me try a different approach: using only observations where we have the true Stress values directly.</p>
<div id="1b73f0fc" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
ALTERNATIVE SUBSET: Low True Stress (Stress &lt;= 2)
============================================================

Number of observations: 9

Subset data:
   Stress  StressSurvey  Time  Anxiety
0       0             0   0.0      0.0
1       0             0   1.0      0.1
2       0             0   1.0      0.1
3       1             3   1.0      1.1
4       1             3   1.0      1.1
5       1             3   1.0      1.1
6       2             6   2.0      2.2
7       2             6   2.0      2.2
8       2             6   2.0      2.2

============================================================
REGRESSION RESULTS ON SUBSET (using TRUE Stress):
============================================================
Intercept (β₀): -0.0000
Coefficient on Stress (β₁): 1.0000
Coefficient on Time (β₂): 0.1000
R-squared: 1.0000

============================================================
TRUE COEFFICIENTS:
============================================================
Intercept (β₀): 0.0
Stress coefficient (β₁): 1.0
Time coefficient (β₂): 0.1

============================================================
STATSMODELS DETAILED OUTPUT:
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.331e+30
Date:                Thu, 06 Nov 2025   Prob (F-statistic):           1.14e-89
Time:                        19:49:05   Log-Likelihood:                 295.66
No. Observations:                   9   AIC:                            -585.3
Df Residuals:                       6   BIC:                            -584.7
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -8.049e-16   1.27e-15     -0.635      0.549    -3.9e-15    2.29e-15
Stress         1.0000   1.31e-15   7.64e+14      0.000       1.000       1.000
Time           0.1000    1.7e-15   5.88e+13      0.000       0.100       0.100
==============================================================================
Omnibus:                        0.038   Durbin-Watson:                   0.076
Prob(Omnibus):                  0.981   Jarque-Bera (JB):                0.204
Skew:                           0.110   Prob(JB):                        0.903
Kurtosis:                       2.296   Cond. No.                         8.70
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
</div>
<p><strong>Better Subset Analysis:</strong></p>
<p>By focusing on the low-stress regime (Stress ≤ 2) where we can use true Stress measurements, we get: - <strong>Intercept (β₀):</strong> 0.0000 ✓ (perfect match) - <strong>Coefficient on Stress (β₁):</strong> 1.0000 ✓ (perfect match) - <strong>Coefficient on Time (β₂):</strong> 0.1000 ✓ (perfect match) - <strong>R-squared:</strong> 1.0 - <strong>Statistical significance:</strong> All coefficients are significant</p>
<p><strong>Visual Diagnostic:</strong></p>
<div id="cell-fig-full-sample-wrong" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div id="fig-full-sample-wrong" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-full-sample-wrong-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-full-sample-wrong-output-1.png" width="662" height="566" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-full-sample-wrong-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Full sample regression showing incorrect Time coefficient
</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-fig-subset-correct" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div id="fig-subset-correct" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-subset-correct-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-subset-correct-output-1.png" width="662" height="566" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-subset-correct-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Subset regression (Stress ≤ 2) showing correct Time coefficient
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Key Insights from Subset Analysis:</strong></p>
<ol type="1">
<li><p><strong>Splitting into regimes works:</strong> By analyzing the low-stress regime separately, we recovered the true coefficients. This demonstrates that non-linearity can be detected and handled by splitting the sample.</p></li>
<li><p><strong>Graphical diagnostics matter:</strong> If we had plotted StressSurvey vs.&nbsp;Stress, we would have seen the non-linearity clearly. Blindly running regression without visual inspection led to the wrong results.</p></li>
<li><p><strong>Statistical significance + correctness:</strong> The subset analysis shows it’s possible to have both statistical significance AND correct coefficients when we choose the right subset.</p></li>
<li><p><strong>Practical implications:</strong> In real research, this suggests:</p>
<ul>
<li>Always plot relationships before regression</li>
<li>Look for different “regimes” in the data</li>
<li>Be skeptical of results that don’t make theoretical sense</li>
<li>Consider whether proxy variables might have non-linear relationships with true variables</li>
</ul></li>
<li><p><strong>The challenge:</strong> In practice, we often don’t have access to the true variable (Stress) to validate our subset choice. This is why graphical diagnostics and theoretical reasoning are so important—they help us identify meaningful subsets even when we can’t directly measure the true relationship.</p></li>
</ol>
<hr>
</section>
<section id="conclusions" class="level2">
<h2 class="anchored" data-anchor-id="conclusions">Conclusions</h2>
<p>This analysis demonstrates several critical lessons about linear regression:</p>
<ol type="1">
<li><p><strong>Statistical significance is necessary but not sufficient:</strong> High R-squared and significant p-values don’t guarantee correct coefficients, especially when non-linearity is present.</p></li>
<li><p><strong>Proxy variables are dangerous:</strong> Even “good” proxies with monotonic relationships can produce completely wrong regression results if they have non-linear relationships with the true variables.</p></li>
<li><p><strong>The sign matters:</strong> Getting the wrong sign on a coefficient (like Time going from +0.1 to -2.7799) can lead to completely opposite policy recommendations and real-world harm.</p></li>
<li><p><strong>Subset analysis helps:</strong> Splitting data into meaningful “statistical regimes” and using graphical diagnostics can reveal problems that full-sample regression misses.</p></li>
<li><p><strong>Real-world consequences are real:</strong> Wrong regression results get published, amplified by media, and used to make policy decisions. The non-linearity problem contributes to the replication crisis and undermines public trust in science.</p></li>
</ol>
<p>The takeaway: <strong>Always visualize relationships, question proxy variables, and be skeptical of results that don’t align with theoretical expectations—even when they’re statistically significant.</strong></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>